In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("train.csv")

In [5]:
df

,Unnamed: 0,index,gene,expression,description,sequence,cleaned_sequence
0,953,133,103161373,0.074376,>NW_003613583.1:2487957-2466471 LOC103161373 [...,TGCAGCCACTGCCCCGGCCGAGCGCGGGCGGAAAACGAAACCGCAG...,ATGGCAAAGTCCCGGGCAGGAAGTTTACAAGGCTCAACGTAA
1,631,8474,100767300,0.047194,>NW_003614457.1:481247-478976 LOC100767300 [or...,ATGGGGCAGACTCAGGTGGTTCAGGAACTGGGAGTAGTGAAAAGTG...,ATGGGGCAGACTCAGGTGGTTCAGGAACTGGGAGTAGTGAAAAGTG...
2,1056,7557,100765254,0.081416,>NW_003614244.1:c830756-830308 LOC100765254 [o...,ATGCTGTGTGGAAGCCGAAGCCACTCTTCCTGGGTGGCCCCTCCGG...,ATGCTGTGTGGAAGCCGAAGCCACTCTTCCTGGGTGGCCCCTCCGG...
3,823,6498,100769774,0.063045,>NW_003614085.1:c1061110-1053520 Nacad [organi...,CATCCACGCCCCCCCCCATCAGAGGGGCGGTGGCCGAGCTGGCTAC...,ATGAAAGCCTGGAGGCAGCAGACAGCATCCTCCAAAGCCTGCAGCT...
4,148,4626,103161433,0.010699,>NW_003613865.1:c345643-334084 LOC103161433 [o...,CGAGGGGCGGGATCCCAAAGTTCAATAAGGAATCCTGGGGCCAGAC...,ATGCGCGGCTCTCCTACTTGCTGA
...,...,...,...,...,...,...,...
10596,12369,6687,100768150,0.682957,>NW_003614115.1:c1112878-925010 Rsu1 [organism...,GGGCGTGGGGGTTGGCCGGGTTTGGTGTGCGCCTGCGCCGATCGCC...,ATGGTCATGAATTCCTCTGGCAGGGGCAGCGCCTCTCCACATCTAG...
10597,12564,4883,100754797,0.708327,>NW_003613890.1:1047872-1042047 Pdrg1 [organis...,CGCCGGAAGTCCTCAGCGCGGCGCGTGCGTGGATAGAGCAGAAGGG...,ATGCTGTCCCCTGAAGCGGAGCGGGTGATGCGGTACCTGGTCGAAG...
10598,12205,5368,100774673,0.663318,>NW_003613933.1:c872402-862998 Mrps33 [organis...,CCGAGGCCCCGCTCCCAGGGAACACTAGTAGTTCCGGGTTGCCCGC...,ATGCATTCAAGATGA
10599,11971,12596,100773964,0.644072,>NW_003617241.1:54299-37751 Clptm1l [organism=...,GGCAGTGCCATGTGGAGAGGAAGCAGCTCCTTCACCAGCTTGGTGG...,ATGTGGAGAGGAAGCAGCTCCTTCACCAGCTTGGTGGTGGGCGTGT...
10600,12361,2232,100754662,0.681790,>NW_003613685.1:2605877-2549492 Adam9 [organis...,ATTTTCAGCAGACAAAGCATCTTTTGTCTTATGAAATTACAACTCC...,ATGAAATTACAACTCCTTGGAGATTAA

In [6]:
df['class'] = pd.cut(df['expression'], 
                         bins=[0, 0.2, 0.4, 0.6, 0.8, 1.0], 
                         labels=[0, 1, 2, 3, 4], 
                         include_lowest=True)

In [7]:
df

,Unnamed: 0,index,gene,expression,description,sequence,cleaned_sequence,class
0,953,133,103161373,0.074376,>NW_003613583.1:2487957-2466471 LOC103161373 [...,TGCAGCCACTGCCCCGGCCGAGCGCGGGCGGAAAACGAAACCGCAG...,ATGGCAAAGTCCCGGGCAGGAAGTTTACAAGGCTCAACGTAA,0
1,631,8474,100767300,0.047194,>NW_003614457.1:481247-478976 LOC100767300 [or...,ATGGGGCAGACTCAGGTGGTTCAGGAACTGGGAGTAGTGAAAAGTG...,ATGGGGCAGACTCAGGTGGTTCAGGAACTGGGAGTAGTGAAAAGTG...,0
2,1056,7557,100765254,0.081416,>NW_003614244.1:c830756-830308 LOC100765254 [o...,ATGCTGTGTGGAAGCCGAAGCCACTCTTCCTGGGTGGCCCCTCCGG...,ATGCTGTGTGGAAGCCGAAGCCACTCTTCCTGGGTGGCCCCTCCGG...,0
3,823,6498,100769774,0.063045,>NW_003614085.1:c1061110-1053520 Nacad [organi...,CATCCACGCCCCCCCCCATCAGAGGGGCGGTGGCCGAGCTGGCTAC...,ATGAAAGCCTGGAGGCAGCAGACAGCATCCTCCAAAGCCTGCAGCT...,0
4,148,4626,103161433,0.010699,>NW_003613865.1:c345643-334084 LOC103161433 [o...,CGAGGGGCGGGATCCCAAAGTTCAATAAGGAATCCTGGGGCCAGAC...,ATGCGCGGCTCTCCTACTTGCTGA,0
...,...,...,...,...,...,...,...,...
10596,12369,6687,100768150,0.682957,>NW_003614115.1:c1112878-925010 Rsu1 [organism...,GGGCGTGGGGGTTGGCCGGGTTTGGTGTGCGCCTGCGCCGATCGCC...,ATGGTCATGAATTCCTCTGGCAGGGGCAGCGCCTCTCCACATCTAG...,3
10597,12564,4883,100754797,0.708327,>NW_003613890.1:1047872-1042047 Pdrg1 [organis...,CGCCGGAAGTCCTCAGCGCGGCGCGTGCGTGGATAGAGCAGAAGGG...,ATGCTGTCCCCTGAAGCGGAGCGGGTGATGCGGTACCTGGTCGAAG...,3
10598,12205,5368,100774673,0.663318,>NW_003613933.1:c872402-862998 Mrps33 [organis...,CCGAGGCCCCGCTCCCAGGGAACACTAGTAGTTCCGGGTTGCCCGC...,ATGCATTCAAGATGA,3
10599,11971,12596,100773964,0.644072,>NW_003617241.1:54299-37751 Clptm1l [organism=...,GGCAGTGCCATGTGGAGAGGAAGCAGCTCCTTCACCAGCTTGGTGG...,ATGTGGAGAGGAAGCAGCTCCTTCACCAGCTTGGTGGTGGGCGTGT...,3
10600,12361,2232,100754662,0.681790,>NW_003613685.1:2605877-2549492 Adam9 [organis...,ATTTTCAGCAGACAAAGCATCTTTTGTCTTATGAAATTACAACTCC...,ATGAAATTACAACTCCTTGGAGATTAA,3

In [9]:
df["class"].value_counts()

class
2    4119
1    2962
0    1969
3    1329
4     222
Name: count, dtype: int64

In [8]:
len(df)/(df["class"].value_counts()*5)

class
2    0.514737
1    0.715800
0    1.076790
3    1.595335
4    9.550450
Name: count, dtype: float64

In [23]:
len(df)/(df["class"].value_counts()*5)

class
2    0.505703
1    0.709333
0    1.090164
3    1.738562
4    8.312500
Name: count, dtype: float64

In [24]:
df["class"].value_counts()

class
2    526
1    375
0    244
3    153
4     32
Name: count, dtype: int64

In [25]:
len(df)

1330

In [26]:
df.to_csv("val_cls.csv")